version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    hostname: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "demo@demo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021!"
    ports:
    - "8082:80"
    networks:
      - n8n-network

networks: 
  n8n-network:
    name: n8n-network
    driver: bridge        