version: '3'

services:

  postgres:
      image: postgres:latest
      container_name: n8n-postgres
      hostname: n8n-postgres
      restart: always
      environment:
        - POSTGRES_DB=
        - POSTGRES_USER=
        - POSTGRES_PASSWORD=
      networks: 
        - n8n-network

networks: 
  n8n-network:
    name: n8n-network
    driver: bridge        